---
- name: Deploy to Tomcat
  hosts: web
  become: yes

  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/lib/jenkins/workspace/2023MavenWebAppAnsible/target/2023MavenWebAppAnsible.war"
        dest: "/opt/tomcat/webapps/2023MavenWebAppAnsible.war"
        remote_src: no

    - name: Restart Tomcat
      shell: |
        /opt/tomcat/bin/shutdown.sh
        /opt/tomcat/bin/startup.sh
